name: frontend
description: CECS 491 Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.8
  http: ^0.13.4
  smooth_star_rating_null_safety: ^1.0.4+2
  toggle_switch: ^1.4.0
  flutter_multi_select_items: ^0.2.1
  carousel_slider: ^4.0.0
  syncfusion_flutter_calendar: ^19.4.54
  currency_text_input_formatter: ^2.1.5
  image_picker: ^0.8.5
  textfield_tags: ^1.4.3
  timelines: ^0.1.0
  timeline_tile: ^2.0.0
  flutter_stripe: ^2.4.0
  stripe_payment: ^1.1.4
  path_provider: ^2.0.9
  # dependencies for notifications
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.1
  cloud_firestore: ^3.1.0
  firebase_messaging: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/
    - assets/mock/
    - assets/images/PieceOfCakeLogo.png
  uses-material-design: true
