// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF2jA-5p7RKQbhQKN3Kb0AalslKrHhE0A',
    appId: '1:514433796390:android:fa2528e31278067b6459e7',
    messagingSenderId: '514433796390',
    projectId: 'cookie-b4cb1',
    storageBucket: 'cookie-b4cb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2JyERAXpk6xE-_Pz6eCIKkZateO0Gi2s',
    appId: '1:514433796390:ios:c6d737ff38e156636459e7',
    messagingSenderId: '514433796390',
    projectId: 'cookie-b4cb1',
    storageBucket: 'cookie-b4cb1.appspot.com',
    iosClientId: '514433796390-c371gni8rhj6t5aodomu44tuncd0h7um.apps.googleusercontent.com',
    iosBundleId: 'com.csulb.frontend',
  );
}
