spring:
  datasource:
    url: jdbc:mysql://149.248.1.131:3306/cookie?useSSL=false
    username: root
    password: cookiecookie
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
